Function Start()
    ' The Init function is generated by wasm2brs and sets up the
    ' memory object as well as the imports, exports, data-sections, etc.
    w2bInit__()
    wasi_init(m.w2b_memory, "cmake.wasm", {})
    w2b__start()
    wasi_shutdown()
End Function

Function GetSettings()
    Return { PauseOnExit: True }
End Function